query FetchFullProfileinfosDataByName {
  profileInfos(where: {name: {_eq: "Bitcoin"}}) {
    id
    rootId
    name
    logo
    descriptionShort
    descriptionLong
    tagLine
    foundingDate
    profileStatusId
    profileSectorId
    profileTypeId
  }
}