query FetchPendingValidations {
  validation(where: {isPending: {_eq: "1"}}) {
    id
    comment
    committedAt
    createdAt
    destinationValue
    field
    isPending
    referencedField
    referencedTable
    resolution
    resolvedAt
    rootId
    rowId
    sourceValue
    tableName
    updatedAt
    updatedFrom
  }
}

