query FetchFullProfileinfosDataById($id: String!) {
  profileInfos(where: {id: {_eq: $id}}) {
    id
    rootId
    name
    logo
    descriptionShort
    descriptionLong
    tagLine
    foundingDate
    profileStatusId
    profileSectorId
    profileTypeId
  }
}
