query FetchFullEntityDataById($id: String2!) {
  entities(where: {id: {_eq: $id}}) {
    id
    leiNumber
    localRegistrationNumber
    name
    rootId
    taxIdentificationNumber
    tradeName
    entityTypeId
    dateOfIncorporation
    countryId
    address
  }
}